### ISSUE TITLE
Problem with umlaut in filename

### ISSUE THREAD

**Issue by GoogleCodeExporter** [RoestVrijStaal/jmupdf#2]
```
What steps will reproduce the problem?
1. try to open a file with umlaut
2.
3.

What is the expected output? What do you see instead?
Error message:
error: cannot open C:\Programme\Test\1329245358432\Test LÃ¶sung.pdf

What version of the product are you using? On what operating system?
3.04

Please provide any additional information below.
Windows PC.

```

Original issue reported on code.google.com by `n3tb...@gmail.com` on 14 Feb 2012 at 7:27

**Comment by GoogleCodeExporter** [comment]
```
Sorry, it is version 3.07
```

Original comment by `n3tb...@gmail.com` on 14 Feb 2012 at 7:28

**Comment by GoogleCodeExporter** [comment]
```
Can you provide a sample PDF?
```

Original comment by `pedro.ri...@gmail.com` on 14 Feb 2012 at 7:55

**Comment by GoogleCodeExporter** [comment]
```
Hi Pedro,
sure :-)
Btw this is the full exception now:
C:\Lösung.pdf
C:\Lösung.pdf
Exception in thread "main" com.jmupdf.exceptions.DocException: Error -2: 
Document null could not be opened.
    at com.jmupdf.pdf.PdfDocument.validate(PdfDocument.java:123)
    at com.jmupdf.pdf.PdfDocument.<init>(PdfDocument.java:32)
    at com.jmupdf.pdf.PdfDocument.<init>(PdfDocument.java:43)
    at com.jmupdf.print.PrintServices.<init>(PrintServices.java:88)
    at PDFs.main(PDFs.java:19)
error: cannot open C:\LÃ¶sung.pdf
```

Original comment by `n3tb...@gmail.com` on 14 Feb 2012 at 8:02

Attachments:
- [Lösung.pdf](https://storage.googleapis.com/google-code-attachments/jmupdf/issue-2/comment-3/Lösung.pdf)

**Comment by GoogleCodeExporter** [comment]
```
Thanks for providing the sample. I have fixed this issue. A new release with 
this fix will be out this week. The latest source is available under the 
"pedro-work" branch.

Thanks,

Pedro
```

Original comment by `pedro.ri...@gmail.com` on 14 Feb 2012 at 10:44

**Comment by GoogleCodeExporter** [comment]
Original comment by `pedro.ri...@gmail.com` on 14 Feb 2012 at 10:50

**Comment by GoogleCodeExporter** [comment]
Original comment by `pedro.ri...@gmail.com` on 14 Feb 2012 at 10:54
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Hi Pedro,

amazing... thanks
```

Original comment by `n3tb...@gmail.com` on 15 Feb 2012 at 9:23
